### PR TITLE
Vertically center align the status bar items

### PR DESCRIPTION
**Pull request by zcysxy**
Before: 

image

After:

image

### CODE REVIEW

**Comment by ceciliamay** [comment]
Changes for the status bar approved!
Quick q - are the settings modal radius mobile reflecting on iPad? Is this for #19 ? 👀

**Comment by zcysxy** [comment]
Haha no. I originally forked this repo to try to fix the issue #19 but failed. And this pull request only change the status bar items alignment.

**Comment by zcysxy** [comment]
Oh feel free to close this pull request if you think the first two commits will mess up the commits history 😂. I should have reverted first.

**Comment by zcysxy** [comment]
Oh I should have change the SCSS source file 🤦🏻

**Pull request closed without merging**
