### PR TITLE
Upgrade theme to obsidian 1.0

### PR DESCRIPTION
**Pull request by hellerbarde**

### CODE REVIEW

**Comment by inhji** [comment]
@hellerbarde The patch by @pastordan also fixes the squished sidebar buttons, maybe you could incorporate these as well :)

https://github.com/ceciliamay/obsidianmd-theme-primary/issues/154#issuecomment-1231864095

**Comment by pastordan** [comment]
George: are you using this code?

.theme-dark .modal .modal-content .vertical-tab-header,
.theme-dark .modal .modal-content .vertical-tab-content-container
.vertical-tab-content {
    background-color: var(--background-secondary) !important;
}

If so, try changing --background-secondary to --background-primary and
see what happens.

**Comment by hellerbarde** [comment]
@GeorgeGo No, you are correct, that is one of the (many) as-of-yet-unresolved issues. (this is after all a "draft" pull request ;) ) I'm not the original theme developer and I'm not familiar with Obsidian theming, so unless Cecilia wants to jump in and push this forward, it'll be somewhat slow going. Additionally, I'll have very limited time this week. 

I'll also quickly mention this: while it is much appreciated to have everyone help with snippets, it would be even more useful for you to also identify the place they might need to go in the original code (inside the `/scss/` folder.)

**Comment by hellerbarde** [comment]
@inhji Thanks a lot for the suggestion, I'm working on incorporating this. Unfortunately, I don't remember how the side ribbon buttons looked originally, especially on hover. *embarrassed*

**Comment by hellerbarde** [comment]
Oh, yeah, I'm aware. I'm just doing this for myself and why not put it out there for y'all.

**Comment by GeorgeGo** [comment]
> Oh, yeah, I'm aware. I'm just doing this for myself and why not put it out there for y'all.

Greatly appreciate the effort. 🙌

**Comment by inhji** [comment]
> @GeorgeGo No, you are correct, that is one of the (many) as-of-yet-unresolved issues. (this is after all a "draft" pull request ;) ) I'm not the original theme developer and I'm not familiar with Obsidian theming, so unless @ceciliamay wants to jump in and push this forward, it'll be somewhat slow going. Additionally, I'll have very limited time this week.
> 
> I'll also quickly mention this: while it is much appreciated to have everyone help with snippets, it would be even more useful for you to also identify the place they might need to go in the original code (inside the `/scss/` folder.)

I'm also not familiar with obsidian themes, but I want to look at the Primary source and see if I can help out. It's just a great theme and I'm missing it. 😄

**Comment by merfed** [comment]
I have been looking and for the life of me cannot figure out why when using split panes, the left pane is offset higher than the right. And then oddly over time both rides will ride upwards.

**Comment by pastordan** [comment]
This bit drove me up a wall too.

**Comment by ceciliamay** [comment]
Hey guys, the new design is a bit challenging with the same reason you guys have mentioned. So I'm pushing all the pull requests to see if these can help! I appreciate all the contributions and the discussion here! I'm also doing a bit of codebase rebuild because I found that some files were a bit all over the place and confusing. I want to open the theme to invite other contributors so that if they want a support a plugin for the theme they can easily do so. I will close and squash this but please feel free to keep the convo going!

**Comment by merfed** [comment]
Scrollbar Fix:

```
Add to _var_global.scss:
--size-2-2: 4px;

Replace in _scrollbars.scss:
body:not(.native-scrollbars) ::-webkit-scrollbar,
body:not(.native-scrollbars) .graph-controls::-webkit-scrollbar {
    visibility: visible;
    width: var(--size-2-2);
    height: var(--size-2-2);
    border-radius: 0;
    display: inherit;
    background: var(--scrollbar-bg);
}

body:not(.native-scrollbars) ::-webkit-scrollbar {
    &-thumb {
        visibility: visible;
        background: var(--scrollbar-thumb-bg);
        border-radius: 0;

        &:active {
            background: var(--scrollbar-active-thumb-bg);
            border-radius: 0;
        }
    }
}
```

I think the scrollbars were just missing the ```---``` before the var name.

**Comment by merfed** [comment]
Fix shifting split panes:

```
Replace in _resize-handles.scss:

&-vertical > * >,
    &-left-split >,
    &-right-split > {
        & .workspace-leaf-resize-handle {
            width: 3px;
            height: 105%;
            // top: -24px;
            border-color: var(--background-modifier-border);
            transition: var(--duration-fast-2)
                        var(--motion-smooth);

            &:hover {
                width: 4px;
                border-color: var(--background-modifier-border);
                transition: var(--duration-fast-2)
                            var(--motion-smooth);
            }

            &:active {
                width: 5px;
                transition: var(--duration-fast-2)
                            var(--motion-smooth);

                .theme-light & { /* VH for Light Mode */
                    border-color: var(--color-l-gray-50);
                }

                .theme-dark & { /* VH for Dark Mode */
                    border-color: var(--color-d-gray-30);
                }
            }
        }
    }
```

**Comment by SalahAdDin** [comment]
How is this going on?

**Comment by gbolo** [comment]
My fav theme by far, thanks @ceciliamay . I hope it gets 1.0 compatibility.

**Review by ceciliamay — APPROVED** [review]
pushing all current PRs! thank you all for your contributions especially @hellerbarde. looking forward to working with the community more! will update everyone here.

**Review by ceciliamay — COMMENTED** [review]
pushing all current PRs! thank you all for your contributions especially @hellerbarde. looking forward to working with the community more! will update everyone here.

**Review by ceciliamay — APPROVED** [review]
pushing all current PRs! thank you all for your contributions especially @hellerbarde. looking forward to working with the community more! will update everyone here.

**Pull request merged**
